version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MODEL_PATH=/app/artifacts
      - GOOGLE_APPLICATION_CREDENTIALS=/app/vietnamese-image-captioning-dd16a6c19d7f.json
    volumes:
      - ./artifacts:/app/artifacts
      - ./vietnamese-image-captioning-dd16a6c19d7f.json:/app/vietnamese-image-captioning-dd16a6c19d7f.json
    
